#!/usr/bin/env fish
# Lavat configuration generated by matugen
# Primary color (hex without #)
set -gx LAVAT_COLOR "{{ colors.primary.default.hex_stripped }}"
# Secondary/rim color
set -gx LAVAT_RIM_COLOR "{{ colors.secondary.default.hex_stripped }}"
# Speed (1-10)
set -gx LAVAT_SPEED "5"
# Radius (1-10)
set -gx LAVAT_RADIUS "5"
# Number of balls (5-20)
set -gx LAVAT_BALLS "10"

# Run lavat with these colors
# Usage: source ~/.config/lavat/config.fish && lavat -g -c $LAVAT_COLOR -k $LAVAT_RIM_COLOR -s $LAVAT_SPEED -r $LAVAT_RADIUS -b $LAVAT_BALLS
