-- Generated by matugen - do not edit manually
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then vim.cmd("syntax reset") end
vim.g.colors_name = "matugen"

local c = {
  bg          = "{{ colors.background.default.hex }}",
  fg          = "{{ colors.on_background.default.hex }}",
  surface     = "{{ colors.surface.default.hex }}",
  surface_var = "{{ colors.surface_variant.default.hex }}",
  surface_mid = "{{ colors.surface_container.default.hex }}",
  surface_hi  = "{{ colors.surface_container_high.default.hex }}",
  on_surface  = "{{ colors.on_surface.default.hex }}",
  primary     = "{{ colors.primary.default.hex }}",
  primary_c   = "{{ colors.primary_container.default.hex }}",
  secondary   = "{{ colors.secondary.default.hex }}",
  secondary_c = "{{ colors.secondary_container.default.hex }}",
  tertiary    = "{{ colors.tertiary.default.hex }}",
  tertiary_c  = "{{ colors.tertiary_container.default.hex }}",
  error       = "{{ colors.error.default.hex }}",
  error_c     = "{{ colors.on_error_container.default.hex }}",
  on_tert_c   = "{{ colors.on_tertiary_container.default.hex }}",
  on_sec_c    = "{{ colors.on_secondary_container.default.hex }}",
  outline     = "{{ colors.outline_variant.default.hex }}",
}

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Editor
hi("Normal",        { fg = c.fg })
hi("NormalFloat",   { fg = c.fg })
hi("NormalNC",      { fg = c.fg })
hi("FloatBorder",   { fg = c.outline })
hi("FloatTitle",    { fg = c.primary,     bold = true })
hi("SignColumn",    { fg = c.surface_var })
hi("LineNr",        { fg = c.surface_var })
hi("CursorLineNr",  { fg = c.primary,     bold = true })
hi("CursorLine",    { bg = c.surface_mid })
hi("ColorColumn",   { bg = c.surface_mid })
hi("Folded",        { fg = c.surface_var })
hi("FoldColumn",    { fg = c.surface_var })
hi("VertSplit",     { fg = c.surface_var })
hi("WinSeparator",  { fg = c.surface_var })
hi("EndOfBuffer",   { fg = c.surface })
hi("NonText",       { fg = c.surface_var })
hi("SpecialKey",    { fg = c.surface_var })
hi("Whitespace",    { fg = c.surface })
hi("StatusLine",    { fg = c.fg })
hi("StatusLineNC",  { fg = c.surface_var })
hi("TabLine",       { fg = c.surface_var })
hi("TabLineFill",   {})
hi("TabLineSel",    { fg = c.bg,          bg = c.primary })

-- Popup menu (nvim built-in + fallback for plugins)
hi("Pmenu",         { fg = c.fg,          bg = c.surface_mid })
hi("PmenuSel",      { fg = c.bg,          bg = c.primary })
hi("PmenuSbar",     { bg = c.surface_var })
hi("PmenuThumb",    { bg = c.primary })
hi("PmenuBorder",   { fg = c.outline,     bg = c.surface_mid })

-- Search
hi("Search",        { fg = c.bg,          bg = c.tertiary })
hi("IncSearch",     { fg = c.bg,          bg = c.primary })
hi("CurSearch",     { fg = c.bg,          bg = c.primary })
hi("Substitute",    { fg = c.bg,          bg = c.error })

-- Visual
hi("Visual",        { bg = c.surface_var })
hi("VisualNOS",     { bg = c.surface_var })

-- Messages
hi("ErrorMsg",      { fg = c.error })
hi("WarningMsg",    { fg = c.tertiary })
hi("MoreMsg",       { fg = c.primary })
hi("Question",      { fg = c.secondary })
hi("ModeMsg",       { fg = c.fg,          bold = true })

-- Diff
hi("DiffAdd",       { fg = c.primary,     bg = c.primary_c })
hi("DiffChange",    { fg = c.secondary,   bg = c.secondary_c })
hi("DiffDelete",    { fg = c.error,       bg = c.error_c })
hi("DiffText",      { fg = c.bg,          bg = c.secondary })

-- Spelling
hi("SpellBad",      { undercurl = true,   sp = c.error })
hi("SpellCap",      { undercurl = true,   sp = c.secondary })
hi("SpellRare",     { undercurl = true,   sp = c.on_tert_c })
hi("SpellLocal",    { undercurl = true,   sp = c.tertiary })

-- Syntax
hi("Comment",       { fg = c.surface_var, italic = true })
hi("Constant",      { fg = c.tertiary })
hi("String",        { fg = c.on_tert_c })
hi("Character",     { fg = c.on_tert_c })
hi("Number",        { fg = c.on_sec_c })
hi("Boolean",       { fg = c.on_tert_c })
hi("Float",         { fg = c.on_sec_c })
hi("Identifier",    { fg = c.fg })
hi("Function",      { fg = c.primary })
hi("Statement",     { fg = c.secondary })
hi("Conditional",   { fg = c.secondary })
hi("Repeat",        { fg = c.secondary })
hi("Label",         { fg = c.secondary })
hi("Operator",      { fg = c.on_sec_c })
hi("Keyword",       { fg = c.secondary,   bold = true })
hi("Exception",     { fg = c.error })
hi("PreProc",       { fg = c.on_tert_c })
hi("Include",       { fg = c.on_tert_c })
hi("Define",        { fg = c.on_tert_c })
hi("Macro",         { fg = c.on_tert_c })
hi("PreCondit",     { fg = c.on_tert_c })
hi("Type",          { fg = c.tertiary })
hi("StorageClass",  { fg = c.tertiary })
hi("Structure",     { fg = c.tertiary })
hi("Typedef",       { fg = c.tertiary })
hi("Special",       { fg = c.on_sec_c })
hi("SpecialChar",   { fg = c.on_sec_c })
hi("Tag",           { fg = c.primary })
hi("Delimiter",     { fg = c.on_surface })
hi("SpecialComment",{ fg = c.surface_var, italic = true })
hi("Debug",         { fg = c.error })
hi("Underlined",    { underline = true })
hi("Ignore",        { fg = c.surface_var })
hi("Error",         { fg = c.error })
hi("Todo",          { fg = c.bg,          bg = c.tertiary, bold = true })

-- Treesitter (modern @-groups)
hi("@comment",            { link = "Comment" })
hi("@string",             { link = "String" })
hi("@number",             { link = "Number" })
hi("@boolean",            { link = "Boolean" })
hi("@float",              { link = "Float" })
hi("@function",           { link = "Function" })
hi("@function.call",      { link = "Function" })
hi("@method",             { link = "Function" })
hi("@method.call",        { link = "Function" })
hi("@keyword",            { link = "Keyword" })
hi("@keyword.function",   { link = "Keyword" })
hi("@keyword.return",     { link = "Keyword" })
hi("@keyword.operator",   { link = "Operator" })
hi("@conditional",        { link = "Conditional" })
hi("@repeat",             { link = "Repeat" })
hi("@type",               { link = "Type" })
hi("@type.builtin",       { link = "Type" })
hi("@variable",           { fg = c.fg })
hi("@variable.builtin",   { fg = c.on_tert_c, italic = true })
hi("@field",              { fg = c.on_sec_c })
hi("@property",           { fg = c.on_sec_c })
hi("@parameter",          { fg = c.fg, italic = true })
hi("@constructor",        { fg = c.tertiary })
hi("@operator",           { link = "Operator" })
hi("@punctuation",        { fg = c.on_surface })
hi("@tag",                { fg = c.secondary })
hi("@tag.attribute",      { fg = c.on_sec_c })
hi("@tag.delimiter",      { fg = c.surface_var })

-- Diagnostics
hi("DiagnosticError",          { fg = c.error })
hi("DiagnosticWarn",           { fg = c.tertiary })
hi("DiagnosticInfo",           { fg = c.secondary })
hi("DiagnosticHint",           { fg = c.on_sec_c })
hi("DiagnosticUnderlineError", { undercurl = true, sp = c.error })
hi("DiagnosticUnderlineWarn",  { undercurl = true, sp = c.tertiary })
hi("DiagnosticUnderlineInfo",  { undercurl = true, sp = c.secondary })
hi("DiagnosticUnderlineHint",  { undercurl = true, sp = c.on_sec_c })

-- blink.cmp
hi("BlinkCmpMenu",            { fg = c.fg })
hi("BlinkCmpMenuBorder",      { fg = c.outline })
hi("BlinkCmpMenuSelection",   { fg = c.bg,       bg = c.primary })
hi("BlinkCmpScrollBarThumb",  { bg = c.primary })
hi("BlinkCmpScrollBarGutter", {})
hi("BlinkCmpLabel",           { fg = c.fg })
hi("BlinkCmpLabelMatch",      { fg = c.primary,  bold = true })
hi("BlinkCmpLabelDeprecated", { fg = c.surface_var, strikethrough = true })
hi("BlinkCmpKind",            { fg = c.secondary })
hi("BlinkCmpDoc",             { fg = c.fg })
hi("BlinkCmpDocBorder",       { fg = c.outline })
hi("BlinkCmpDocSeparator",    { fg = c.outline })
hi("BlinkCmpSignatureHelp",   { fg = c.fg })
hi("BlinkCmpSignatureHelpBorder", { fg = c.outline })
hi("BlinkCmpGhostText",       { fg = c.surface_var })

-- snacks.nvim
hi("SnacksNormal",            { fg = c.fg })
hi("SnacksDashboardNormal",   { fg = c.fg })
hi("SnacksPickerNormal",      { fg = c.fg })
hi("SnacksPickerBorder",      { fg = c.outline })
hi("SnacksPickerList",        { fg = c.fg })
hi("SnacksPickerListCursorLine", { bg = c.surface_mid })
hi("SnacksPickerPreview",     { fg = c.fg })
hi("SnacksPickerPreviewBorder", { fg = c.outline })
hi("SnacksPickerTitle",       { fg = c.bg,       bg = c.primary, bold = true })
hi("SnacksPickerMatch",       { fg = c.primary,  bold = true })
hi("SnacksPickerDir",         { fg = c.surface_var })
hi("SnacksPickerPrompt",      { fg = c.primary })
hi("SnacksNotifierNormal",    { fg = c.fg })
hi("SnacksNotifierBorder",    { fg = c.outline })
hi("SnacksIndent",            { fg = c.surface })
hi("SnacksIndentScope",       { fg = c.surface_var })

-- noice.nvim
hi("NoiceCmdlinePopup",       { fg = c.fg })
hi("NoiceCmdlinePopupBorder", { fg = c.outline })
hi("NoiceCmdlineIcon",        { fg = c.primary })
hi("NoicePopup",              { fg = c.fg })
hi("NoicePopupBorder",        { fg = c.outline })
hi("NoiceMini",               { fg = c.fg })
hi("NoiceConfirm",            { fg = c.fg })
hi("NoiceConfirmBorder",      { fg = c.outline })

-- which-key.nvim
hi("WhichKeyNormal",          { fg = c.fg })
hi("WhichKeyBorder",          { fg = c.outline })
hi("WhichKeyTitle",           { fg = c.primary,  bold = true })
hi("WhichKey",                { fg = c.primary })
hi("WhichKeyDesc",            { fg = c.fg })
hi("WhichKeySeparator",       { fg = c.surface_var })
hi("WhichKeyGroup",           { fg = c.secondary, bold = true })

-- trouble.nvim
hi("TroubleNormal",           { fg = c.fg,       bg = c.bg })
hi("TroubleNormalNC",         { fg = c.fg,       bg = c.bg })

-- gitsigns
hi("GitSignsAdd",             { fg = c.primary })
hi("GitSignsChange",          { fg = c.tertiary })
hi("GitSignsDelete",          { fg = c.error })
